# Generated by Django 5.2.1 on 2026-05-22 05:28

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcqapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberMachineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('role', models.CharField(choices=[('attacker', 'Attacker'), ('victim', 'Victim'), ('monitor', 'Monitor')], max_length=20)),
                ('base_box', models.CharField(max_length=255)),
                ('memory_mb', models.IntegerField(default=2048)),
                ('cpu_count', models.IntegerField(default=2)),
                ('gui_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CyberPracticalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('total_marks', models.IntegerField(default=100)),
                ('variable_schema', models.JSONField(blank=True, default=dict)),
                ('attacker_init_template', models.TextField()),
                ('victim_init_template', models.TextField()),
                ('monitor_init_template', models.TextField(blank=True, null=True)),
                ('verify_template', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_practical_tasks', to='mcqapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CyberSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('verification_output', models.TextField(blank=True, null=True)),
                ('verification_details', models.JSONField(blank=True, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('failed', 'Failed')], db_index=True, default='starting', max_length=20)),
                ('history_path', models.CharField(blank=True, max_length=500, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cyberpracticalapp.cyberpracticaltask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CyberMachineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('attacker', 'Attacker'), ('victim', 'Victim'), ('monitor', 'Monitor')], max_length=20)),
                ('vm_name', models.CharField(max_length=255)),
                ('vm_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('guacamole_connection_id', models.CharField(blank=True, max_length=255, null=True)),
                ('guacamole_url', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('failed', 'Failed'), ('destroyed', 'Destroyed')], default='starting', max_length=20)),
                ('recording_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberpracticalapp.cybermachinetemplate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='cyberpracticalapp.cybersession')),
            ],
        ),
        migrations.CreateModel(
            name='CyberTopology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('network_name', models.CharField(default='cyberlab-net', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attacker_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker_topologies', to='cyberpracticalapp.cybermachinetemplate')),
                ('monitor_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_topologies', to='cyberpracticalapp.cybermachinetemplate')),
                ('victim_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_topologies', to='cyberpracticalapp.cybermachinetemplate')),
            ],
        ),
        migrations.AddField(
            model_name='cyberpracticaltask',
            name='topology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cyberpracticalapp.cybertopology'),
        ),
    ]
