# Generated by Django 5.2.1 on 2026-05-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpracticalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HypervisorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('vagrant', 'Vagrant'), ('proxmox', 'Proxmox')], default='vagrant', max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('max_students', models.IntegerField(default=50)),
                ('current_students', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CyberEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('verify', 'Verify'), ('attack', 'Attack'), ('defense', 'Defense')], max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cyberpracticalapp.cybermachinesession')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberpracticalapp.cybersession')),
            ],
        ),
    ]
