# Generated by Django 5.2.1 on 2026-05-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpracticalapp', '0002_hypervisornode_cybereventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybermachinetemplate',
            name='default_password',
            field=models.CharField(default='vagrant', max_length=100),
        ),
        migrations.AddField(
            model_name='cybermachinetemplate',
            name='default_username',
            field=models.CharField(default='vagrant', max_length=100),
        ),
        migrations.AddField(
            model_name='cybermachinetemplate',
            name='extra_disk_gb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cybermachinetemplate',
            name='os_type',
            field=models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=50),
        ),
    ]
