# Generated by Django 5.2.1 on 2026-06-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpracticalapp', '0003_cybermachinetemplate_default_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cybermachinesession',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cybermachinesession',
            name='username',
        ),
        migrations.AddField(
            model_name='cybermachinesession',
            name='generated_password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cybermachinesession',
            name='generated_username',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
