# Generated by Django 5.2.1 on 2026-01-02 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubjectenrollment',
            name='enrolled_at',
        ),
        migrations.AlterField(
            model_name='studentsubjectenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
