# Generated by Django 5.2.1 on 2026-01-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0004_question_explanation_alter_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exams', to='mcqapp.question'),
        ),
    ]
