# Generated by Django 5.2.1 on 2026-01-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0005_exam_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='terminate_reason',
            field=models.CharField(blank=True, choices=[('time_up', 'Time Up'), ('warnings', 'Warnings Limit'), ('manual', 'Manual Submit')], max_length=20, null=True),
        ),
    ]
