# Generated by Django 5.2.1 on 2026-01-12 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_otp', to=settings.AUTH_USER_MODEL),
        ),
    ]
