# Generated by Django 5.2.1 on 2025-06-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_practicalexam_practicalexamsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('strict', 'Strict'), ('practical', 'Practical')], default='practice', max_length=10),
        ),
    ]
