# Generated by Django 5.2.1 on 2025-06-17 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('command_template', models.TextField(help_text='Template command for the task')),
                ('expected_output', models.TextField(help_text='Expected output pattern (regex)')),
                ('marks', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='examsession',
            name='terminal_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('strict', 'Strict'), ('practical', 'Practical')], default='practice', max_length=10),
        ),
        migrations.CreateModel(
            name='ExamPracticalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.practicaltask')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('exam', 'task')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='practical_tasks',
            field=models.ManyToManyField(through='main.ExamPracticalTask', to='main.practicaltask'),
        ),
        migrations.CreateModel(
            name='PracticalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_used', models.TextField()),
                ('output', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examsession')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.practicaltask')),
            ],
            options={
                'unique_together': {('session', 'task')},
            },
        ),
    ]
