# Generated by Django 5.2.1 on 2025-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_exam_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='task_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
