# Generated by Django 5.2.1 on 2025-05-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_question_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=10),
        ),
    ]
