# Generated by Django 5.2.1 on 2025-06-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_question_correct_option'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('exam__mode', 'strict'), ('is_completed', False)), fields=('student', 'exam'), name='unique_strict_session'),
        ),
    ]
