# Generated by Django 5.2.1 on 2025-06-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_exam_question_count_exam_task_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='task_count',
        ),
    ]
