# Generated by Django 5.2.1 on 2025-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_exam_task_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='practical_exams',
            field=models.ManyToManyField(blank=True, to='main.practicalexam'),
        ),
    ]
