# Generated by Django 5.2.1 on 2025-06-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_examsession_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examsession',
            name='unique_strict_session',
        ),
        migrations.AddField(
            model_name='examsession',
            name='elapsed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
