# Generated by Django 5.2.1 on 2025-06-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exam_practical_exams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicalexamsession',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(through='main.ExamQuestion', to='main.question'),
        ),
        migrations.AddField(
            model_name='practicalexam',
            name='allowed_commands',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed commands (empty for all)'),
        ),
        migrations.AddField(
            model_name='practicalexam',
            name='environment_vars',
            field=models.JSONField(blank=True, default=dict, help_text='Environment variables (JSON key-value pairs)'),
        ),
        migrations.AlterField(
            model_name='practicalexam',
            name='docker_image',
            field=models.CharField(default='redhat/ubi8:latest', help_text='Docker image to use for the exam', max_length=255),
        ),
        migrations.AlterField(
            model_name='practicalexam',
            name='setup_command',
            field=models.TextField(default="echo 'Environment ready'", help_text='Command to run when session starts'),
        ),
        migrations.AlterField(
            model_name='practicalexam',
            name='verification_command',
            field=models.TextField(default="echo 'Verification complete'", help_text='Command to verify solution'),
        ),
        migrations.AlterField(
            model_name='practicalexamresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.practicalexamsession'),
        ),
    ]
