# Generated by Django 5.2.1 on 2025-06-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_examsession_unique_strict_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='elapsed_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('student', 'exam')},
        ),
    ]
