# Generated by Django 5.2.1 on 2025-06-27 11:18

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_practicalexamsession_options_exam_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalexamsession',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=100, unique=True),
        ),
    ]
