# Generated by Django 5.2.1 on 2025-07-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_practicalexamsession_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicalexamresult',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='practicalexamresult',
            name='total_possible',
            field=models.FloatField(),
        ),
    ]
