# Generated by Django 5.2.1 on 2025-07-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_practicalexamresult_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalexamsession',
            name='startup_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicalexamsession',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('failed', 'Failed')], default='starting', max_length=20),
        ),
    ]
