# Generated by Django 5.2.1 on 2025-08-14 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_practicalexamsession_startup_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
