# Generated by Django 5.2.1 on 2025-08-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_subject_students_user_subjects'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
