# Generated by Django 5.2.1 on 2025-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicalexam',
            name='allowed_commands',
        ),
        migrations.RemoveField(
            model_name='practicalexam',
            name='docker_image',
        ),
        migrations.RemoveField(
            model_name='practicalexamsession',
            name='container_id',
        ),
        migrations.AddField(
            model_name='practicalexam',
            name='base_vm',
            field=models.CharField(default='Redhat', help_text='Name of the base VirtualBox VM to clone', max_length=255),
        ),
        migrations.AddField(
            model_name='practicalexam',
            name='snapshot_name',
            field=models.CharField(default='clean', help_text='Snapshot to use for cloning', max_length=100),
        ),
        migrations.AddField(
            model_name='practicalexamsession',
            name='vm_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicalexamsession',
            name='vm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='practicalexam',
            name='setup_command',
            field=models.TextField(default="echo 'Environment ready'", help_text='Command to run when VM starts'),
        ),
    ]
