# Generated by Django 5.2.1 on 2025-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_practicalexam_allowed_commands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicalexam',
            name='base_vm',
        ),
        migrations.RemoveField(
            model_name='practicalexam',
            name='snapshot_name',
        ),
        migrations.RemoveField(
            model_name='practicalexamsession',
            name='vm_ip',
        ),
        migrations.AddField(
            model_name='practicalexam',
            name='allowed_commands',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed commands (empty for all)'),
        ),
        migrations.AddField(
            model_name='practicalexam',
            name='vm_base_name',
            field=models.CharField(default='Redhat', help_text='Base VM name to clone from', max_length=255),
        ),
        migrations.AddField(
            model_name='practicalexam',
            name='vm_password',
            field=models.CharField(default='exampass', help_text='Password to access the VM', max_length=100),
        ),
        migrations.AddField(
            model_name='practicalexam',
            name='vm_snapshot',
            field=models.CharField(default='base_snapshot', help_text='Snapshot to use for cloning', max_length=255),
        ),
        migrations.AddField(
            model_name='practicalexam',
            name='vm_username',
            field=models.CharField(default='examuser', help_text='Username to access the VM', max_length=100),
        ),
        migrations.AddField(
            model_name='practicalexamsession',
            name='ssh_port',
            field=models.IntegerField(blank=True, help_text='SSH port for VM access', null=True),
        ),
        migrations.AlterField(
            model_name='practicalexam',
            name='setup_command',
            field=models.TextField(default="echo 'Environment ready'", help_text='Command to run when session starts'),
        ),
    ]
