# Generated by Django 5.2.1 on 2026-01-20 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcqapp', '0008_alter_emailotp_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('snapshot_name', models.CharField(max_length=100)),
                ('verify_command', models.TextField()),
                ('expected_output', models.CharField(max_length=200)),
                ('total_marks', models.IntegerField(default=10)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_exams', to='mcqapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=120, unique=True)),
                ('vm_ip', models.GenericIPAddressField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='running', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicalapp.practicaltask')),
            ],
        ),
    ]
