# Generated by Django 5.2.1 on 2026-02-09 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicalapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicalsession',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='practicalsession',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('failed', 'Failed')], db_index=True, default='starting', max_length=20),
        ),
        migrations.AlterField(
            model_name='practicalsession',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='practicalapp.practicaltask'),
        ),
        migrations.AlterField(
            model_name='practicalsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='practicalsession',
            index=models.Index(fields=['user', 'status'], name='practicalap_user_id_d76645_idx'),
        ),
        migrations.AddIndex(
            model_name='practicalsession',
            index=models.Index(fields=['vm_name'], name='practicalap_vm_name_474672_idx'),
        ),
        migrations.AddConstraint(
            model_name='practicalsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['starting', 'running'])), fields=('user',), name='one_active_practical_per_user'),
        ),
    ]
