# Generated by Django 5.2.1 on 2026-01-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicalsession',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='starting', max_length=20),
        ),
        migrations.AlterField(
            model_name='practicalsession',
            name='vm_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicalsession',
            name='vm_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
