# Generated by Django 5.2.1 on 2026-02-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicalapp', '0002_alter_practicalsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalsession',
            name='history_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
