# Generated by Django 5.2.1 on 2026-02-13 10:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicalapp', '0003_practicalsession_history_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicaltask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='practicaltask',
            name='snapshot_name',
        ),
        migrations.AddField(
            model_name='practicaltask',
            name='ddescription',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
