# Generated by Django 5.2.1 on 2026-02-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicalapp', '0004_remove_practicaltask_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicaltask',
            old_name='ddescription',
            new_name='description',
        ),
    ]
