# Generated by Django 5.2.1 on 2026-02-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicalapp', '0005_rename_ddescription_practicaltask_description'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='practicalsession',
            name='practicalap_user_id_d76645_idx',
        ),
        migrations.RemoveIndex(
            model_name='practicalsession',
            name='practicalap_vm_name_474672_idx',
        ),
        migrations.AddField(
            model_name='practicalsession',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practicalsession',
            name='verification_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicalsession',
            name='verification_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicaltask',
            name='init_script',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='practicaltask',
            name='verify_script',
            field=models.TextField(),
        ),
    ]
