# Generated by Django 5.2.1 on 2026-02-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicalapp', '0006_remove_practicalsession_practicalap_user_id_d76645_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicaltask',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
