Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"
  config.vm.hostname = "exam-8876db"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: "192.168.56.105"

  config.ssh.insert_key = false
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "exam-8876db"
    vb.memory = 2048
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--firmware", "efi"]
  end
end